#!/usr/bin/env python3
import subprocess

def tmux_sessions():
    tmux_list_sessions_cmd = "tmux list-sessions"
    output = subprocess.Popen(tmux_list_sessions_cmd.split(), 
                              stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE,
                              encoding="utf-8").stdout.readlines()
    tmux_session_list = [line.split(":")[0] for line in output]
    if len(tmux_session_list) == 0:
        print(f"Error: no sever running on tmux")
    else:
        for id, session in enumerate(tmux_session_list, start = 1):
            print(f"Session [{id}]: {session}")
    return tmux_session_list

def tmux_events(tmux_session_list):
    session_input = input("> ")
    try:
        session_input_int = int(session_input)
    except:
        print("Please key in the right session id")
    else:
        if session_input_int <= len(tmux_session_list):
            session_name = tmux_session_list[session_input_int - 1]
            print(f"Attaching session [{session_input}]: {session_name}")
            session_attach_cmd = f"tmux attach -t {session_name}"
            output = subprocess.Popen(session_attach_cmd.split(), 
                                  stdout=subprocess.PIPE).communicate()
        else:
            print("Please key in the right session id")



if __name__ == "__main__":
    tmux_list = tmux_sessions()
    if len(tmux_list):
        tmux_events(tmux_list)
